import yagmail

# You need to create a password for sending email from app.
# You can refer this URL for more details
# https://support.google.com/accounts/answer/185833?visit_id=638536253756293760-2827421503&p=InvalidSecondFactor&rd=1
# Connecting to the email id and the password and it is getting yag object.
yag=yagmail.SMTP("kcharankumar@gmail.com", "password generated by Google for your mail id")

#Send email from yag object by giving the details.
yag.send(
    to="kcharankumar@gmail.com",
    subject="Hello, How are you..",
    contents="This is a test mail from python"
)

print ('EMail is send successfully..')
